### ISSUE TITLE
afl-collect - ImportError: No module named queue

### ISSUE THREAD

**Issue by matterpreter** [rc0r/afl-utils#47]
Hey there,

I'm hitting an issue after setup completes where afl-collect won't run due to a missing "queue" module. I can't seem to find this Python module or one that would provide it.  I am running Python 2.7 and have tested with 3.5.

```
root@afl-bench:~# afl-collect
Traceback (most recent call last):
  File "/usr/local/bin/afl-collect", line 4, in <module>
    __import__('pkg_resources').run_script('afl-utils==1.32a0', 'afl-collect')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/afl_utils-1.32a0-py2.7.egg/EGG-INFO/scripts/afl-collect", line 20, in <module>

  File "build/bdist.linux-i686/egg/afl_utils/afl_collect.py", line 19, in <module>
ImportError: No module named queue
```

**Comment by rc0r** [comment]
We do not support Python 2.7. As of Python 3 the `queue` module is part of the standard library (https://docs.python.org/3.5/library/queue.html). (It was renamed from `Queue` in Python 2.)

Could you rerun:

```
python3 setup.py install
```

And after that try to run `afl-collect` again?

**Comment by matterpreter** [comment]
Yep, that seems to have worked. Thanks!
